//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtDriversFromLogs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<Language name=\"English\">\r\n  <mainForm>\r" +
            "\n    <colTruck>Truck</colTruck>\r\n    <colTag>Tag</colTag>\r\n    <colNickname>Game" +
            " Nickname</colNickname>\r\n    <colGameID>Game ID</colGameID>\r\n    <groupOpen>Open" +
            " log</groupOpen>\r\n    <btnOpen>From today</btnOpen>\r\n    <btnOpenYesterday>From " +
            "yesterday</btnOpenYesterday>\r\n    <btnOpenAnother>Open file</btnOpenAnother>\r\n  " +
            "  <selectGame>Select game</selectGame>\r\n    <groupSearch>Search</groupSearch>\r\n " +
            "   <btnOptions>Options</btnOptions>\r\n    <btnExit>Exit</btnExit>\r\n    <menuOpenP" +
            "rofile>Open profile</menuOpenProfile>\r\n    <menuCopyName>Copy nickname</menuCopy" +
            "Name>\r\n    <menuCopyID>Copy ID</menuCopyID>\r\n  </mainForm>\r\n  <optionsForm>\r\n   " +
            " <tabMain>Main</tabMain>\r\n    <tabAdv>Advanced</tabAdv>\r\n    <groupLanguage>Lang" +
            "uage</groupLanguage>\r\n    <groupOptionSearch>Search options</groupOptionSearch>\r" +
            "\n    <chckById>Search by ID</chckById>\r\n    <chckByTag>Search by Tag</chckByTag>" +
            "\r\n    <chckCCase>Case sensitive characters</chckCCase>\r\n    <btnSave>Save</btnSa" +
            "ve>\r\n    <grpPersonalDir>Personal dir</grpPersonalDir>\r\n    <btnPersonalDir>Sele" +
            "ct dir</btnPersonalDir>\r\n    <groupRegLine>Regular expression line</groupRegLine" +
            ">\r\n    <lblRegAttention>Do not modify unless you know what it is!</lblRegAttenti" +
            "on>\r\n    <btnRestore>Restore parameters</btnRestore>\r\n  </optionsForm>\r\n  <messa" +
            "ges>\r\n    <msgNoFile>Log file {0} doesn\'t exist!</msgNoFile>\r\n    <msgEnterToReg" +
            "Line>Attention, this string can break the program!</msgEnterToRegLine>\r\n  </mess" +
            "ages>\r\n</Language>")]
        public global::System.Xml.XmlDocument Language {
            get {
                return ((global::System.Xml.XmlDocument)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 200")]
        public global::System.Drawing.Point windowPositon {
            get {
                return ((global::System.Drawing.Point)(this["windowPositon"]));
            }
            set {
                this["windowPositon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 300")]
        public global::System.Drawing.Size windowSize {
            get {
                return ((global::System.Drawing.Size)(this["windowSize"]));
            }
            set {
                this["windowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chckCCase {
            get {
                return ((bool)(this["chckCCase"]));
            }
            set {
                this["chckCCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtSearchLine {
            get {
                return ((string)(this["txtSearchLine"]));
            }
            set {
                this["txtSearchLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chckSearchByID {
            get {
                return ((bool)(this["chckSearchByID"]));
            }
            set {
                this["chckSearchByID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chckSearchByTag {
            get {
                return ((bool)(this["chckSearchByTag"]));
            }
            set {
                this["chckSearchByTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"\[(?<tHours>[\d{2}]+):(?<tMinutes>[\d{2}]+):(?<tSeconds>[\d{2}]+)\]\s+Spawning\s+GameTruck\s+\((?<name>.+)\((?<gameID>\d+)\)\s+-\s+(TruckersMP\s+ID:|TMPID:\s|ETS2MPId:)(?<ets2mpID>\d+)(?<adInfo>.*)\)\s+Additional\s+data:\s+(?<adData>.+)[\s\S]\[00\]\s+.+\s+.\/def\/vehicle\/truck\/(?<truck>.+)\/data.sii.")]
        public string regPattern {
            get {
                return ((string)(this["regPattern"]));
            }
            set {
                this["regPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gameATS {
            get {
                return ((bool)(this["gameATS"]));
            }
            set {
                this["gameATS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string personalDir {
            get {
                return ((string)(this["personalDir"]));
            }
            set {
                this["personalDir"] = value;
            }
        }
    }
}
